#pragma once

#if UE_BUILD_DEVELOPMENT
  #define FLYFF_AUTH_PORT_DEFAULT 4000
  #define FLYFF_GAME_PORT_DEFAULT 7777
  #define FLYFF_LOBBY_PORT_DEFAULT 7778
#else
  #define FLYFF_AUTH_PORT_DEFAULT 4000
  #define FLYFF_GAME_PORT_DEFAULT 27015
  #define FLYFF_LOBBY_PORT_DEFAULT 27016
#endif

#ifndef FLYFF_AUTH_PORT
  #define FLYFF_AUTH_PORT FLYFF_AUTH_PORT_DEFAULT
#endif
#ifndef FLYFF_GAME_PORT
  #define FLYFF_GAME_PORT FLYFF_GAME_PORT_DEFAULT
#endif
#ifndef FLYFF_LOBBY_PORT
  #define FLYFF_LOBBY_PORT FLYFF_LOBBY_PORT_DEFAULT
#endif
